#https ??
#server:
#  ssl:
#    key-store-password: 5509kong
#    key-store-type: PKCS12
#    key-store:  classpath:keystore.p12


spring:
  h2:
    console:
      enabled: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  #  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:db
#    password:
#    username: sa

  datasource:
    url: jdbc:mysql://godchoice.co1d2mlhpaa6.ap-northeast-2.rds.amazonaws.com:3306/godchoice
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: 5509kong


  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        #나중에 지워야함
#    hibernate:
#      ddl-auto: create-drop

  #h2 테이블 만들어지는 규칙?
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ENC(GRwC4xDK2+Li+1SoOSTQjPCUBW1RBhQIEsPlm21/u1VCOQI4L0UzvwfBEQsnJ+vJ)
            redirect-uri: http://3.38.255.232/member/signup/kakao
#            redirect-uri: http://localhost:8080/member/signup/kakao
            client-authentication-method: POST
            client-secret: ENC(J4KeBmKJFYx1iNmpI0Lx4DUUziK07zu3Qyzrb+Ph0IZRhvZXMyEM9NQaheLsw0PM)
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: kakao
          google:
            client-id: ENC(1cFCCJjbyqD6w9HK/+KLcHh0i3njhzV8z7X+u/zaA48PdBNPK29WChD1omoL//bIB7Gi7YGy+KopL6gQnZOZACQYdugGenR9rgIY572eCSnrzktFmglrHA==)
            client-secret: ENC(VmYADJ+wPrqPUX+36AXjnBuAbP0TR9XT3EIcSd3RtTAH4VriQi2cA0hMAAl4atgD)
            scope:
              - profile
              - email
              - openid
          github :
            client-id: ENC(kPT+Y+wbyQ33X2pxj8883ic6543VJ28mMF0u6wH85Gg=)
            client-secret: ENC(LoQHy5dVgo+rHIXp51+8P03fgkZpWcv6a1lL186yLhZJkiM1NeSSL6jnN0e70Zgn6jw3IecNG3Q=)
          naver:
            authorization-grant-type: authorization_code
#            redirect-uri: http://3.38.255.232/member/signup/naver
            redirect-uri: http://localhost:8080/member/signup/naver
            client-id: ENC(0AO0EaRVFK2ckWeWvfxYU5D+X2mGqstJymsN2ATI024=)
            client-secret: ENC(NQHyfJtQu7G5IfgZfko3e9WZte3HYjS1)
            client-name: naver

        provider:
          kakao :
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: kakao_account
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-info-uri: https://openapi.naver.com/v1/nid/me
            token-uri: https://nid.naver.com/oauth2.0/token
            user-name-attribute: naver_account
  profiles:
    include: secret



jwt :
  secret:
    key : ENC(tlpTNg1TYeUptcB4XxvUNWsvuz5CF2BgcHsrKTaFMbTagKjtCyY2/7GXPL+jqTc9eJapoEvm/3mVlxaKwQItMKrd2zlwo5jyN58VTFodm6t6Jqn7QOSR91MGQug19AgRMoNNO9v9xyabpnjawL22hL63yFRj+m+QP6nHposThKk6QmhYRNh7v75i6XjN58ER5aZX5FzQDRPPR1IA+N52jjOtFXw9pzf8+IDiRf7ptAJEjQTDjhFJ0x1TO7n467qcuL0zNt19jxVS61k5YmvOHWGXabAHTxnXZSp/4Fx5OMHNXO5MsXYs2YnvNZQb3MBCzjhQkNFH8hc+1nRtsMauCXXGx+u5AQWN)

jasypt:
  secret:
    key: "my_jasypt_key"