#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          naver:
#            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
#            authorization-grant-type: authorization_code
#            client-secret: zk9ebNHQld
#            scope: email, useruserName, useruseruserImgUrlUrlUrl, sex
#            client-id: BeFF2BLXGHQ26lS7FEd0
#            client-name: Naver
#        provider:
#          naver:
#            user-name-attribute: response
#            authorization-uri: https://nid.naver.com/oauth2.0/authorize
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            token-uri: https://nid.naver.com/oauth2.0/token

# 구글이나 페이스북은 안적어도 되는데, 네이버나 카카오는 적어줘야함(기본 제공 provider가 아니기 때문에)
spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost/login/oauth2/code/naver
            client-secret: zk9ebNHQld
            client-id: BeFF2BLXGHQ26lS7FEd0
            client-name: Naver
# Naver Provider 등록!
spring:
  security:
    oauth2:
      client:
        provider:
          naver:
            user-name-attribute: 'response'
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-info-uri: https://openapi.naver.com/v1/nid/me
            token-uri: https://nid.naver.com/oauth2.0/token
