server:
  ssl:
    key-store-password: 5509kong
    key-store-type: PKCS12
    key-store:  classpath:keystore.p12

spring:
  profiles:
    include: secret

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:mysql://godchoice.co1d2mlhpaa6.ap-northeast-2.rds.amazonaws.com:3306/godchoice
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: ENC(OJgXyE93hux1qu+gy/WRyc8d0Z1XgGtX)

  jpa:
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true

    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

  security:
    oauth2:
      client:
        registration:
          kakao:
#            redirect-uri: http://localhost:8080/member/signup/kakao
            redirect-uri: https://godchoice.shop/member/signup/kakao
#            redirect-uri: http://localhost:3000/member/signup/kakao
            client-id: ENC(GRwC4xDK2+Li+1SoOSTQjPCUBW1RBhQIEsPlm21/u1VCOQI4L0UzvwfBEQsnJ+vJ)
            client-secret: ENC(J4KeBmKJFYx1iNmpI0Lx4DUUziK07zu3Qyzrb+Ph0IZRhvZXMyEM9NQaheLsw0PM)
            authorization-grant-type: authorization_code
            client-name: kakao

          google:
            redirect-uri: https://godchoice.shop/member/signup/google
#            redirect-uri: http://localhost:3000/member/signup/google
            client-id: ENC(1cFCCJjbyqD6w9HK/+KLcHh0i3njhzV8z7X+u/zaA48PdBNPK29WChD1omoL//bIB7Gi7YGy+KopL6gQnZOZACQYdugGenR9rgIY572eCSnrzktFmglrHA==)
            client-secret: ENC(VmYADJ+wPrqPUX+36AXjnBuAbP0TR9XT3EIcSd3RtTAH4VriQi2cA0hMAAl4atgD)

          github :
#            redirect-uri: http://localhost:3000/member/signup/github
            redirect-uri: https://godchoice.shop/member/signup/github
            client-id: ENC(kPT+Y+wbyQ33X2pxj8883ic6543VJ28mMF0u6wH85Gg=)
            client-secret: ENC(LoQHy5dVgo+rHIXp51+8P03fgkZpWcv6a1lL186yLhZJkiM1NeSSL6jnN0e70Zgn6jw3IecNG3Q=)

          naver:
            redirect-uri: https://godchoice.shop/member/signup/naver
#            redirect-uri: http://localhost:3000/member/signup/naver
            client-id: ENC(tB0Oc2vPBULZObHGk1UQnx+ZDNCmptVlXhp2xOpofYU=)
            client-secret: ENC(1Ox6O24XdWClCPdhil4/42Pn6vFSQJZ6)
            authorization-grant-type: authorization_code
            client-name: naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: kakao_account
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-info-uri: https://openapi.naver.com/v1/nid/me
            token-uri: https://nid.naver.com/oauth2.0/token
            user-name-attribute: naver_account

jwt :
  secret:
    key : ENC(tlpTNg1TYeUptcB4XxvUNWsvuz5CF2BgcHsrKTaFMbTagKjtCyY2/7GXPL+jqTc9eJapoEvm/3mVlxaKwQItMKrd2zlwo5jyN58VTFodm6t6Jqn7QOSR91MGQug19AgRMoNNO9v9xyabpnjawL22hL63yFRj+m+QP6nHposThKk6QmhYRNh7v75i6XjN58ER5aZX5FzQDRPPR1IA+N52jjOtFXw9pzf8+IDiRf7ptAJEjQTDjhFJ0x1TO7n467qcuL0zNt19jxVS61k5YmvOHWGXabAHTxnXZSp/4Fx5OMHNXO5MsXYs2YnvNZQb3MBCzjhQkNFH8hc+1nRtsMauCXXGx+u5AQWN)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

sentry:
  logging:
    minimum-event-level: warn
  dsn: https://d247bc84b40c4f9c9780a16db53b7da3@o4504194608201728.ingest.sentry.io/4504194610364416