spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            client-secret: zk9ebNHQld
            scope: email, userName, userImgUrl, sex
            client-id: BeFF2BLXGHQ26lS7FEd0
            client-name: Naver
        provider:
          naver:
            user-name-attribute: response
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-info-uri: https://openapi.naver.com/v1/nid/me
            token-uri: https://nid.naver.com/oauth2.0/token
