#https ??
#server:
#  ssl:
#    key-store-password: 5509kong
#    key-store-type: PKCS12
#    key-store:  classpath:keystore.p12
server:
  port: 8080

spring:
  h2:
    console:
      enabled: true

  # --- application-oauth.yml 추가
  profiles:
    includes: oauth

  datasource:
    driver-class-: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

    properties:
      hibernate:
        format_sql: true
        show_sql: true
        #나중에 지워야함

#h2 테이블 만들어지는 규칙?
    hibernate:
      ddl-auto: create-drop
  #    hibernate:
  #      ddl-auto: update

jwt :
  secret:
    key : ENC(7ZvmGsATO2+bqAzJhy/kEiwcy2nogu5wkrycMRH28TrtLcELCTlUWMF7DgoPQlNHaaTEg+RliXgecU8+jHQX8I4q80NLvlN/LC1FdVhIxQZ+EdV8LaePnXhhv1zasVCpSibJwBYz2NnTrq/QnCSH3+GXlOhz6ymBkiQlevS2BGnJGN5eqc4ilq+1p41+VSqQwGyRT9DBSSBSySWoafBubywqT+30P+8848UsguUy1yMcFM/i/bvDjl53Mo5IZeBQRUdrKlB+8XhoHNa0ps06QiwieYLQbcV5NUuIp1s6r+HdlJa4rlciCR0ETFeO0pwrQGWER0f357domOc0rwjf1NIyvG+/JmKj)

jasypt:
  secret:
    key: "my_jasypt_key"