#https ??
#server:
#  ssl:
#    key-store-password: 5509kong
#    key-store-type: PKCS12
#    key-store:  classpath:keystore.p12

spring:
  h2:
    console:
      enabled: true

  # --- application-oauth.yml 추가
  profiles:
    includes: oauth

  datasource:
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

    properties:
      hibernate:
        format_sql: true
        show_sql: true
        #나중에 지워야함

#h2 테이블 만들어지는 규칙?
    hibernate:
      ddl-auto: create-drop
  #    hibernate:
  #      ddl-auto: update

jwt :
  secret:
    key : ENC(tlpTNg1TYeUptcB4XxvUNWsvuz5CF2BgcHsrKTaFMbTagKjtCyY2/7GXPL+jqTc9eJapoEvm/3mVlxaKwQItMKrd2zlwo5jyN58VTFodm6t6Jqn7QOSR91MGQug19AgRMoNNO9v9xyabpnjawL22hL63yFRj+m+QP6nHposThKk6QmhYRNh7v75i6XjN58ER5aZX5FzQDRPPR1IA+N52jjOtFXw9pzf8+IDiRf7ptAJEjQTDjhFJ0x1TO7n467qcuL0zNt19jxVS61k5YmvOHWGXabAHTxnXZSp/4Fx5OMHNXO5MsXYs2YnvNZQb3MBCzjhQkNFH8hc+1nRtsMauCXXGx+u5AQWN)

jasypt:
  secret:
    key: "my_jasypt_key"

#google login
google:
  auth:
    url: 'https://oauth2.googleapis.com'
    scope: 'profile,email,openid'
  login:
    url: 'https://accounts.google.com'
  redirect:
    uri: 'http://localhost:8080/google/login/redirect'D
  client:
    id: ENC(1cFCCJjbyqD6w9HK/+KLcHh0i3njhzV8z7X+u/zaA48PdBNPK29WChD1omoL//bIB7Gi7YGy+KopL6gQnZOZACQYdugGenR9rgIY572eCSnrzktFmglrHA==)
  secret: ENC(VmYADJ+wPrqPUX+36AXjnBuAbP0TR9XT3EIcSd3RtTAH4VriQi2cA0hMAAl4atgD)
